// Sandbox: an in-process Postgres loaded with a replica of the live schema.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { PGlite } from '@electric-sql/pglite'

const here = path.dirname(fileURLToPath(import.meta.url))
export const schemaDir = path.join(here, 'schema')

const short = (e) => String(e?.message ?? e).split('\n')[0].slice(0, 220)

// Roles, the auth/net/extensions schemas and helpers Supabase provides.
const PRELUDE = `
  create role anon nologin;
  create role authenticated nologin;
  create role service_role nologin bypassrls;
  create schema if not exists auth;
  create schema if not exists extensions;
  create schema if not exists net;
  create schema if not exists storage;

  -- Supabase hands every new table/view/function in public to the API roles.
  alter default privileges in schema public grant all on tables to anon, authenticated, service_role;
  alter default privileges in schema public grant all on sequences to anon, authenticated, service_role;
  alter default privileges in schema public grant all on functions to anon, authenticated, service_role;

  -- Just enough of Storage to test object policies.
  create table storage.buckets (id text primary key, public boolean default false, file_size_limit bigint, allowed_mime_types text[]);
  create table storage.objects (id uuid primary key default gen_random_uuid(), bucket_id text not null, name text not null, owner uuid);
  alter table storage.objects enable row level security;
  create function storage.foldername(name text) returns text[] language sql immutable as $$
    select (string_to_array(name, '/'))[1:array_length(string_to_array(name, '/'), 1) - 1] $$;
  insert into storage.buckets (id) values ('payment-proofs');
  grant usage on schema storage to anon, authenticated, service_role;
  grant all on storage.objects, storage.buckets to authenticated, service_role;
  grant execute on function storage.foldername(text) to anon, authenticated, service_role;

  create table auth.users (id uuid primary key default gen_random_uuid(), email text);
  create function auth.uid() returns uuid language sql stable as $$
    select coalesce(nullif(current_setting('request.jwt.claim.sub', true), ''),
                    (nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'sub'))::uuid
  $$;
  create table net.sent (id bigserial primary key, url text, headers jsonb, body jsonb);
  create function net.http_post(url text, headers jsonb default '{}', body jsonb default '{}', timeout_milliseconds int default 5000)
    returns bigint language plpgsql as $$ declare i bigint; begin
      insert into net.sent (url, headers, body) values (url, headers, body) returning id into i; return i; end $$;
  create function public.gen_random_bytes(n int) returns bytea language sql as $$
    select decode(substr(md5(random()::text) || md5(random()::text) || md5(random()::text), 1, n * 2), 'hex') $$;
  create sequence public.client_account_seq;
  create function public.generate_client_referral_code() returns text language sql as $$ select upper(substr(md5(random()::text), 1, 8)) $$;
`

/** Runs a list of statements one by one so a single failure does not hide the rest. */
async function runEach(db, label, statements, failures) {
  for (const sql of statements) {
    if (!sql.trim()) continue
    try {
      await db.exec(sql)
    } catch (e) {
      failures.push(`${label}: ${short(e)} :: ${sql.slice(0, 90).replace(/\s+/g, ' ')}`)
    }
  }
}

const split = (file) =>
  fs
    .readFileSync(path.join(schemaDir, file), 'utf8')
    .split(/;\n(?=create |alter |CREATE |ALTER )/)
    .map((s) => (s.trim().endsWith(';') ? s : s + ';'))

export async function createDb({ withPolicies = true } = {}) {
  const db = new PGlite()
  const failures = []
  await db.exec(PRELUDE)

  await runEach(db, 'tables', split('01_tables.sql'), failures)
  // The dump flattens identity columns; audit_log.id is one of them.
  await db.exec(`alter table public.audit_log alter column id add generated by default as identity;`)
  await runEach(db, 'pk_unique', split('02_pk_unique.sql'), failures)
  await runEach(db, 'checks', split('03_checks.sql'), failures)
  await runEach(db, 'fks', split('04_fks.sql'), failures)
  await runEach(db, 'indexes', split('05_indexes.sql'), failures)
  // SQL-language functions validate their bodies when created, which breaks on
  // ordering and on tables the sandbox does not carry. They are checked when run.
  await db.exec(`set check_function_bodies = off;`)
  await runEach(db, 'functions', split('06_functions.sql'), failures)
  await db.exec(`set check_function_bodies = on;`)
  await runEach(db, 'triggers', split('07_triggers.sql'), failures)

  // Every table gets RLS (as on Supabase) and customers/staff get table access.
  const { rows } = await db.query(`select tablename from pg_tables where schemaname = 'public'`)
  for (const { tablename } of rows) {
    await db.exec(`alter table public."${tablename}" enable row level security;`)
  }
  if (withPolicies) await runEach(db, 'policies', split('08_policies.sql'), failures)

  // Storage policies as they are in production today.
  await db.exec(`
    create policy payment_proofs_customer_delete on storage.objects for delete to authenticated
      using ((bucket_id = 'payment-proofs'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text));
    create policy payment_proofs_customer_insert on storage.objects for insert to authenticated
      with check ((bucket_id = 'payment-proofs'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text));
    create policy payment_proofs_customer_select on storage.objects for select to authenticated
      using ((bucket_id = 'payment-proofs'::text) AND (((storage.foldername(name))[1] = (auth.uid())::text) OR (EXISTS (
        SELECT 1 FROM public.tenant_users tu WHERE ((tu.user_id = auth.uid()) AND (tu.role = ANY (ARRAY['admin'::text, 'accounting'::text])))))));
  `)
  // Tables outside the replica that the hygiene migration indexes, plus the stock view.
  await db.exec(`
    create table public.inventory_items (id uuid primary key default gen_random_uuid(), tenant_id uuid, sku text, name text, category text, unit text,
      quantity_on_hand numeric, reorder_level numeric, location text, is_active boolean default true);
    create table public.inventory_kit_items (id uuid primary key default gen_random_uuid(), item_id uuid references public.inventory_items(id));
    create table public.inventory_movements (id uuid primary key default gen_random_uuid(), replaced_item_id uuid references public.inventory_items(id));
    create table public.ratings (id uuid primary key default gen_random_uuid(), client_id uuid references public.clients(id));
    create table public.repair_job_crew (id uuid primary key default gen_random_uuid(), added_by uuid references auth.users(id));
    create table public.staff_email_verified (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id));
    create table public.client_site_photos (id uuid primary key default gen_random_uuid(), client_id uuid);
    create index client_site_photos_client_id_idx on public.client_site_photos (client_id);
    create index idx_client_site_photos_client_id on public.client_site_photos (client_id);
    create table public.repair_photos (id uuid primary key default gen_random_uuid(), repair_id uuid);
    create index repair_photos_repair_id_idx on public.repair_photos (repair_id);
    create index idx_repair_photos_repair_id on public.repair_photos (repair_id);
    alter table public.inventory_items enable row level security;
    create view public.inventory_catalog with (security_barrier = true) as
      select id, tenant_id, sku, name, category, unit, quantity_on_hand, reorder_level, location
      from public.inventory_items i where is_active;
  `)
  // Production revoked anonymous writes; anything created later keeps the defaults.
  await db.exec(`revoke insert, update, delete, truncate on all tables in schema public from anon;`)

  await db.exec(`
    grant usage on schema public, auth to anon, authenticated, service_role;
    grant all on all tables in schema public to authenticated, service_role;
    grant all on all sequences in schema public to authenticated, service_role;
    grant execute on all functions in schema public to authenticated, service_role;
    grant select on auth.users to authenticated, service_role;
    alter table public.billing force row level security;
  `)
  await db.exec(`alter table public.billing no force row level security;`)

  // Production keeps the money / staff functions away from signed-in users.
  await db.exec(`
    revoke execute on function
      public.verify_payment_submission_as(uuid, uuid),
      public.reject_payment_submission_as(uuid, uuid, text, text),
      public.run_billing_automation(integer),
      public.release_stale_jobs(),
      public.team_push(uuid, text, text),
      public.activate_due_scheduled_plan_changes()
    from public, anon, authenticated;
  `)

  return { db, failures }
}

/** Runs `fn` as an end user (RLS applies) and always restores the superuser. */
export async function asUser(db, userId, fn) {
  await db.exec(`select set_config('request.jwt.claims', '{"sub":"${userId}","role":"authenticated"}', false); set role authenticated;`)
  try {
    return await fn()
  } finally {
    await db.exec(`reset role; select set_config('request.jwt.claims', '', false);`)
  }
}

export const msg = short
