alter table public.audit_log add constraint audit_log_pkey PRIMARY KEY (id);
alter table public.auto_pay_enrollments add constraint auto_pay_enrollments_pkey PRIMARY KEY (id);
alter table public.billing add constraint billing_pkey PRIMARY KEY (id);
alter table public.billing_cycle_settings add constraint billing_cycle_settings_pkey PRIMARY KEY (id);
alter table public.billing_cycle_settings add constraint billing_cycle_settings_cycle_code_key UNIQUE (cycle_code);
alter table public.billing_reminders_sent add constraint billing_reminders_sent_pkey PRIMARY KEY (billing_id, kind);
alter table public.client_services add constraint client_services_pkey PRIMARY KEY (id);
alter table public.clients add constraint clients_pkey PRIMARY KEY (id);
alter table public.internet_plans add constraint internet_plans_pkey PRIMARY KEY (id);
alter table public.payment_submissions add constraint payment_submissions_pkey PRIMARY KEY (id);
alter table public.payments add constraint payments_pkey PRIMARY KEY (id);
alter table public.push_config add constraint push_config_pkey PRIMARY KEY (id);
alter table public.referral_rewards add constraint referral_rewards_pkey PRIMARY KEY (id);
alter table public.referral_withdrawals add constraint referral_withdrawals_pkey PRIMARY KEY (id);
alter table public.referrals add constraint referrals_pkey PRIMARY KEY (id);
alter table public.repair_records add constraint repair_records_pkey PRIMARY KEY (id);
alter table public.service_requests add constraint service_requests_pkey PRIMARY KEY (id);
alter table public.tenant_users add constraint tenant_users_pkey PRIMARY KEY (user_id);
alter table public.tenants add constraint tenants_pkey PRIMARY KEY (id);
