alter table public.auto_pay_enrollments add constraint auto_pay_enrollments_payment_method_check CHECK ((payment_method = ANY (ARRAY['GCash'::text, 'Bank Transfer'::text])));
alter table public.billing add constraint billing_amount_due_nonnegative CHECK (((amount_due IS NULL) OR (amount_due >= (0)::numeric)));
alter table public.billing add constraint billing_discount_amount_nonnegative CHECK (((discount_amount IS NULL) OR (discount_amount >= (0)::numeric)));
alter table public.billing add constraint billing_final_amount_nonnegative CHECK (((final_amount IS NULL) OR (final_amount >= (0)::numeric)));
alter table public.billing add constraint billing_original_amount_nonnegative CHECK (((original_amount IS NULL) OR (original_amount >= (0)::numeric)));
alter table public.client_services add constraint client_services_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'active'::text, 'suspended'::text, 'terminated'::text, 'cancelled'::text])));
alter table public.payment_submissions add constraint payment_submissions_amount_claimed_check CHECK ((amount_claimed > (0)::numeric));
alter table public.payment_submissions add constraint payment_submissions_payment_method_check CHECK ((payment_method = ANY (ARRAY['GCash'::text, 'Bank Transfer'::text, 'Cash'::text])));
alter table public.payment_submissions add constraint payment_submissions_status_check CHECK ((status = ANY (ARRAY['Pending'::text, 'Verified'::text, 'Rejected'::text])));
alter table public.payments add constraint payments_amount_paid_nonnegative CHECK (((amount_paid IS NULL) OR (amount_paid >= (0)::numeric)));
alter table public.push_config add constraint push_config_id_check CHECK (id);
alter table public.referral_rewards add constraint referral_rewards_amount_check CHECK ((amount > (0)::numeric));
alter table public.referral_rewards add constraint referral_rewards_status_check CHECK ((status = ANY (ARRAY['Pending'::text, 'Eligible'::text, 'Withdrawn'::text, 'Cancelled'::text])));
alter table public.referral_withdrawals add constraint referral_withdrawal_amount_check CHECK (((gross_amount = 250.00) AND (transfer_fee = 5.00) AND (net_amount = 245.00)));
alter table public.referral_withdrawals add constraint referral_withdrawal_status_check CHECK ((status = ANY (ARRAY['Pending'::text, 'Processing'::text, 'Paid'::text, 'Rejected'::text, 'Cancelled'::text])));
alter table public.repair_records add constraint repair_records_job_type_check CHECK ((job_type = ANY (ARRAY['repair'::text, 'installation'::text])));
alter table public.service_requests add constraint service_requests_type_check CHECK ((request_type = ANY (ARRAY['plan_change'::text, 'new_service'::text, 'repair'::text, 'help'::text])));
alter table public.service_requests add constraint service_requests_plan_check CHECK (((requested_plan IS NULL) OR (requested_plan = ANY (ARRAY['G1_P500'::text, 'G1_P750'::text, 'G1_P1000'::text, 'G1_P1250'::text, 'G1_P1500'::text, 'G1_P2000'::text]))));
alter table public.service_requests add constraint service_requests_installation_location_type_check CHECK ((installation_location_type = ANY (ARRAY['current'::text, 'other'::text])));
