alter table public.audit_log add constraint audit_log_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id);
alter table public.auto_pay_enrollments add constraint auto_pay_enrollments_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
alter table public.auto_pay_enrollments add constraint auto_pay_enrollments_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.billing add constraint billing_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id);
alter table public.billing add constraint billing_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
alter table public.client_services add constraint client_services_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES internet_plans(id);
alter table public.client_services add constraint client_services_billing_cycle_id_fkey FOREIGN KEY (billing_cycle_id) REFERENCES billing_cycle_settings(id);
alter table public.client_services add constraint client_services_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
alter table public.client_services add constraint client_services_technician_user_id_fkey FOREIGN KEY (technician_user_id) REFERENCES auth.users(id);
alter table public.client_services add constraint client_services_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
alter table public.clients add constraint clients_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.clients add constraint clients_referred_by_client_id_fkey FOREIGN KEY (referred_by_client_id) REFERENCES clients(id) ON DELETE SET NULL;
alter table public.payment_submissions add constraint payment_submissions_service_request_id_fkey FOREIGN KEY (service_request_id) REFERENCES service_requests(id) ON DELETE CASCADE;
alter table public.payment_submissions add constraint payment_submissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.payment_submissions add constraint payment_submissions_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
alter table public.payment_submissions add constraint payment_submissions_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE SET NULL;
alter table public.payment_submissions add constraint payment_submissions_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id);
alter table public.payments add constraint payments_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id);
alter table public.payments add constraint payments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(id);
alter table public.payments add constraint payments_billing_id_fkey FOREIGN KEY (billing_id) REFERENCES billing(id);
alter table public.payments add constraint payments_service_request_id_fkey FOREIGN KEY (service_request_id) REFERENCES service_requests(id) ON DELETE SET NULL;
alter table public.referral_rewards add constraint referral_rewards_withdrawal_id_fkey FOREIGN KEY (withdrawal_id) REFERENCES referral_withdrawals(id) ON DELETE SET NULL;
alter table public.referral_rewards add constraint referral_rewards_referral_id_fkey FOREIGN KEY (referral_id) REFERENCES referrals(id) ON DELETE RESTRICT;
alter table public.referral_rewards add constraint referral_rewards_referrer_client_id_fkey FOREIGN KEY (referrer_client_id) REFERENCES clients(id) ON DELETE RESTRICT;
alter table public.referral_withdrawals add constraint referral_withdrawals_referral_id_fkey FOREIGN KEY (referral_id) REFERENCES referrals(id) ON DELETE RESTRICT;
alter table public.referral_withdrawals add constraint referral_withdrawals_referrer_client_id_fkey FOREIGN KEY (referrer_client_id) REFERENCES clients(id) ON DELETE RESTRICT;
alter table public.referrals add constraint referrals_referrer_client_id_fkey FOREIGN KEY (referrer_client_id) REFERENCES clients(id) ON DELETE CASCADE;
alter table public.referrals add constraint referrals_referred_client_id_fkey FOREIGN KEY (referred_client_id) REFERENCES clients(id) ON DELETE SET NULL;
alter table public.repair_records add constraint repair_records_technician_user_id_fkey FOREIGN KEY (technician_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.repair_records add constraint repair_records_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
alter table public.repair_records add constraint repair_records_service_request_id_fkey FOREIGN KEY (service_request_id) REFERENCES service_requests(id) ON DELETE SET NULL;
alter table public.service_requests add constraint service_requests_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
alter table public.service_requests add constraint service_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.service_requests add constraint service_requests_referred_by_client_id_fkey FOREIGN KEY (referred_by_client_id) REFERENCES clients(id) ON DELETE SET NULL;
alter table public.tenant_users add constraint tenant_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
