CREATE INDEX idx_clients_user_id ON public.clients USING btree (user_id);
CREATE INDEX idx_clients_tenant_id ON public.clients USING btree (tenant_id);
CREATE UNIQUE INDEX clients_referral_code_unique_idx ON public.clients USING btree (referral_code);
CREATE UNIQUE INDEX clients_account_id_uniq ON public.clients USING btree (account_id) WHERE (account_id IS NOT NULL);
CREATE INDEX idx_client_services_tenant_id ON public.client_services USING btree (tenant_id);
CREATE INDEX idx_client_services_client_id ON public.client_services USING btree (client_id);
CREATE INDEX idx_client_services_plan_id ON public.client_services USING btree (plan_id);
CREATE INDEX idx_client_services_technician_user_id ON public.client_services USING btree (technician_user_id);
CREATE INDEX idx_client_services_billing_cycle_id ON public.client_services USING btree (billing_cycle_id);
CREATE INDEX idx_client_services_status ON public.client_services USING btree (status);
CREATE INDEX idx_billing_client_id ON public.billing USING btree (client_id);
CREATE INDEX idx_billing_tenant_client ON public.billing USING btree (tenant_id, client_id);
CREATE INDEX idx_billing_tenant_status ON public.billing USING btree (tenant_id, status);
CREATE INDEX idx_billing_client_due_date ON public.billing USING btree (client_id, due_date);
CREATE UNIQUE INDEX uq_billing_tenant_bill_id ON public.billing USING btree (tenant_id, bill_id) WHERE (bill_id IS NOT NULL);
CREATE UNIQUE INDEX uq_billing_tenant_client_period ON public.billing USING btree (tenant_id, client_id, billing_period_start, billing_period_end) WHERE ((billing_period_start IS NOT NULL) AND (billing_period_end IS NOT NULL));
CREATE INDEX idx_billing_tenant_period ON public.billing USING btree (tenant_id, billing_period_start, billing_period_end);
CREATE INDEX idx_payments_client_id ON public.payments USING btree (client_id);
CREATE INDEX payments_service_request_id_idx ON public.payments USING btree (service_request_id);
CREATE INDEX idx_payments_tenant_billing ON public.payments USING btree (tenant_id, billing_id);
CREATE INDEX idx_payments_client_date ON public.payments USING btree (client_id, payment_date DESC);
CREATE INDEX idx_payments_tenant_date ON public.payments USING btree (tenant_id, payment_date DESC);
CREATE UNIQUE INDEX uq_payments_tenant_payment_id ON public.payments USING btree (tenant_id, payment_id) WHERE (payment_id IS NOT NULL);
CREATE UNIQUE INDEX uq_payments_tenant_receipt_number ON public.payments USING btree (tenant_id, receipt_number) WHERE (receipt_number IS NOT NULL);
CREATE INDEX idx_payments_service_request_id ON public.payments USING btree (service_request_id);
CREATE INDEX idx_payments_billing_id ON public.payments USING btree (billing_id);
CREATE INDEX payment_submissions_client_idx ON public.payment_submissions USING btree (client_id, created_at DESC);
CREATE INDEX payment_submissions_request_idx ON public.payment_submissions USING btree (service_request_id, created_at DESC);
CREATE INDEX payment_submissions_status_idx ON public.payment_submissions USING btree (status, created_at DESC);
CREATE INDEX service_requests_user_id_idx ON public.service_requests USING btree (user_id);
CREATE INDEX service_requests_client_id_idx ON public.service_requests USING btree (client_id);
CREATE INDEX service_requests_status_idx ON public.service_requests USING btree (status);
CREATE INDEX service_requests_created_at_idx ON public.service_requests USING btree (created_at DESC);
CREATE INDEX service_requests_client_type_status_idx ON public.service_requests USING btree (client_id, request_type, status);
CREATE INDEX idx_service_requests_plan_change ON public.service_requests USING btree (client_id, request_type, status);
CREATE INDEX idx_service_requests_effective_at ON public.service_requests USING btree (effective_at) WHERE (request_type = 'plan_change'::text);
CREATE INDEX referrals_referrer_client_id_idx ON public.referrals USING btree (referrer_client_id);
CREATE INDEX referrals_bonus_status_idx ON public.referrals USING btree (bonus_status);
CREATE INDEX referral_rewards_referrer_client_id_idx ON public.referral_rewards USING btree (referrer_client_id);
CREATE INDEX referral_rewards_referral_id_idx ON public.referral_rewards USING btree (referral_id);
CREATE INDEX referral_rewards_status_idx ON public.referral_rewards USING btree (status);
CREATE UNIQUE INDEX referral_withdrawals_referral_id_unique ON public.referral_withdrawals USING btree (referral_id);
CREATE INDEX referral_withdrawals_referrer_client_id_idx ON public.referral_withdrawals USING btree (referrer_client_id);
CREATE INDEX referral_withdrawals_status_idx ON public.referral_withdrawals USING btree (status);
CREATE INDEX idx_repair_records_client_id ON public.repair_records USING btree (client_id);
CREATE INDEX idx_repair_records_repair_date ON public.repair_records USING btree (repair_date DESC);
CREATE INDEX repair_records_client_id_idx ON public.repair_records USING btree (client_id);
CREATE INDEX idx_repair_records_technician_user_id ON public.repair_records USING btree (technician_user_id);
CREATE UNIQUE INDEX repair_records_service_request_uniq ON public.repair_records USING btree (service_request_id) WHERE (service_request_id IS NOT NULL);
