CREATE TRIGGER clients_account_id_trigger BEFORE INSERT ON public.clients FOR EACH ROW EXECUTE FUNCTION assign_client_account_id();
CREATE TRIGGER clients_audit_trail AFTER UPDATE ON public.clients FOR EACH ROW EXECUTE FUNCTION log_client_changes();
CREATE TRIGGER clients_technician_guard BEFORE UPDATE ON public.clients FOR EACH ROW EXECUTE FUNCTION guard_technician_client_update();
CREATE TRIGGER payment_submission_verification_trigger BEFORE UPDATE OF status ON public.payment_submissions FOR EACH ROW EXECUTE FUNCTION payment_submission_verification_trigger();
CREATE TRIGGER payment_submission_push_trigger AFTER UPDATE OF status ON public.payment_submissions FOR EACH ROW EXECUTE FUNCTION notify_payment_result();
CREATE TRIGGER payment_submission_tenant_trigger BEFORE INSERT ON public.payment_submissions FOR EACH ROW EXECUTE FUNCTION set_payment_submission_tenant();
CREATE TRIGGER payment_submission_updated_at_trigger BEFORE UPDATE ON public.payment_submissions FOR EACH ROW EXECUTE FUNCTION update_payment_submission_timestamp();
CREATE TRIGGER payments_billing_status_trigger AFTER INSERT OR UPDATE OF billing_id, amount_paid ON public.payments FOR EACH ROW EXECUTE FUNCTION sync_billing_status_from_payment();
CREATE TRIGGER payments_plan_activation_trigger AFTER INSERT OR UPDATE OF amount_paid, service_request_id ON public.payments FOR EACH ROW EXECUTE FUNCTION payments_plan_activation_trigger();
CREATE TRIGGER payment_activate_plan AFTER INSERT ON public.payments FOR EACH ROW EXECUTE FUNCTION activate_plan_after_payment();
CREATE TRIGGER repair_record_sync_before BEFORE UPDATE ON public.repair_records FOR EACH ROW EXECUTE FUNCTION repair_record_sync();
CREATE TRIGGER installation_job_done_after AFTER UPDATE OF status ON public.repair_records FOR EACH ROW EXECUTE FUNCTION installation_job_done();
CREATE TRIGGER repair_job_accepted_sms_trigger AFTER UPDATE OF technician_user_id ON public.repair_records FOR EACH ROW EXECUTE FUNCTION notify_job_accepted();
CREATE TRIGGER repair_record_status_after AFTER UPDATE OF status ON public.repair_records FOR EACH ROW EXECUTE FUNCTION repair_record_status_to_request();
CREATE TRIGGER service_request_referral_trigger BEFORE INSERT OR UPDATE ON public.service_requests FOR EACH ROW EXECUTE FUNCTION populate_service_request_referral();
CREATE TRIGGER service_request_repair_record_trigger AFTER INSERT ON public.service_requests FOR EACH ROW EXECUTE FUNCTION repair_request_to_record();
CREATE TRIGGER service_request_updated_at_trigger BEFORE UPDATE ON public.service_requests FOR EACH ROW EXECUTE FUNCTION update_service_request_timestamp();
CREATE TRIGGER service_request_customer_guard BEFORE UPDATE ON public.service_requests FOR EACH ROW EXECUTE FUNCTION guard_service_request_update();
CREATE TRIGGER service_request_plan_amount_trigger BEFORE INSERT OR UPDATE OF request_type, requested_plan, requested_amount ON public.service_requests FOR EACH ROW EXECUTE FUNCTION snapshot_plan_change_amount();
CREATE TRIGGER service_request_plan_application_trigger AFTER INSERT ON public.service_requests FOR EACH ROW EXECUTE FUNCTION plan_application_to_submission();
CREATE TRIGGER service_request_plan_cancel_trigger AFTER UPDATE OF status ON public.service_requests FOR EACH ROW EXECUTE FUNCTION plan_application_cancelled();
